---
title: "Materials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Example

- [html](nestedCC/exNestedCC.html)
- [Rmd](nestedCC/exNestedCC.Rmd)
- [cohort.txt](nestedCC/cohort.txt)


## Wednesday Morning

1. Lesson: Getting Started
2. Lecture: [Introduction](DayOne/introduction.html){target="_blank"}
3. Lesson: Functions Part I ([.Rmd](DayOne/Functions-part1.Rmd){target="_blank"} / [.html](DayOne/Functions-part1.html){target="_blank"})

## Lunch

## Wednesday Afternoon

1. Documentation ([.Rmd](DayOne/Documentation.Rmd){target="_blank"} / [.html](DayOne/Documentation.html){target="_blank"})
2. Functions Part II ([.Rmd](DayOne/Functions-part2.Rmd){target="_blank"} / [.html](DayOne/Functions-part2.html){target="_blank"})
3. Version control ([Slides](DayOne/git.html){target="_blank"})

## Thursday Morning

1. Lesson: Object oriented programming ([.Rmd](DayTwo/OOP.Rmd) / [.html](DayTwo/OOP.html))
2. Lesson: Functional Programming ([.Rmd](DayTwo/functional.Rmd) / [.html](DayTwo/functional.html))
3. Lecture: R package ecosystem overview ([Slides](DayTwo/Ecology.html))

## Lunch

## Thursday Afternoon

1. Debugging ([.Rmd](DayTwo/Debugging.Rmd) / [.html](DayTwo/Debugging.html))
2. Approaches to software development ([Slides](DayTwo/software-dev-lecture.pdf))
3. Testing and CRAN checks ([.Rmd](DayTwo/testing.Rmd) / [.html](DayTwo/testing.html))

## Friday Morning

1. Designing a package ([Slides](DayThree/design.html))
2. Working with other packages ([Slides](DayThree/PlayingNice.html))
3. Publishing and promoting your package ([Slides](DayThree/publishing.html))


